name: Build and Release APK

on:
  push:
    branches:
      - master  # Triggers on push to master branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        run: ./gradlew --version

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Debug APK File Structure
        run: ls -R app/build/outputs/apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Create GitHub Release
    needs: build  # Run only after build job succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.${{ github.run_number }}
          name: "Release v1.${{ github.run_number }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.GITHUB_TOKEN }}
