name: Build and Release APK

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Grants permission to create releases

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Tag
        run: |
          TAG_NAME=v1.${{ github.run_number }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download APK Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}  # Fix: Use the generated tag
          files: app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.GITHUB_TOKEN }}
